Minor tweak to get it building on cygwin.
Previously failed with:
.libs/fplll.o:fplll.cpp:(.text$_ZN5fplll6MatGSOINS_4Z_NRIA1_12__mpz_structEENS_5FP_NRIeEEE12updateGSORowEii[_ZN5fplll6MatGSOINS_4Z_NRIA1_12__mpz_structEENS_5FP_NRIeEEE12updateGSORowEii]+0xba): undefined reference to `fplll::FP_NR<long double>::is_nan() const'

due to instantiation of a long double template.